version: '3.4'

services:
  db:
    hostname: db
    restart: always
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: Pass@word
    volumes:
      - pgdata-diplomski:/var/lib/postgresql/data

  realestateapi:
    ports:
      - "5019:80"

volumes:
  pgdata-diplomski:
    external: false